# Generated by Django 3.2.8 on 2022-08-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=64)),
                ('postcode', models.CharField(max_length=64)),
                ('street', models.CharField(max_length=64)),
                ('house_number', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=24)),
                ('gis', models.CharField(max_length=64)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rating_counter', models.IntegerField(default=0)),
                ('delivery_time', models.CharField(max_length=64, null=True)),
                ('delivery_price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('minimum_order_price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('free_delivery', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('restaurants', models.ManyToManyField(to='app_restaurant.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('restaurants', models.ManyToManyField(to='app_restaurant.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sections', models.ManyToManyField(to='app_restaurant.Section')),
            ],
        ),
    ]
